trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

services:
- postgres:latest
  env:
    POSTGRES_DB: flask
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: root123
  ports:
  - 5432:5432

jobs:
- job: Build
  displayName: 'Build and Push Docker Image'
  steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      docker build -t my-ekart-app .
    displayName: 'Build Docker image'

  - task: Docker@2
    displayName: 'Push Docker image to Docker Hub'
    inputs:
      containerRegistry: 'DockerHubConnection' # Assumes you've set up Docker Hub service connection in Azure DevOps
      repository: 'harnoor81/my-ekart-app'
      command: 'login'
      customCommand: 'logout' # Optional, if you want to logout after pushing

  - script: |
      docker tag my-ekart-app:latest harnoor81/my-ekart-app:latest
      docker push harnoor81/my-ekart-app:latest
    displayName: 'Push Docker image'
